config/routes.rb
Rails.application.routes.draw do
  # get 'products/index'
  devise_for :users
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  get 'products/place_order', to: 'products#place_order', as: 'place_order'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :products 
  root 'products#index'
  resources :products
  root to: 'products#index'
  resources :comments
  resources :orders 
  post 'orders/paypal/create_payment'  => 'orders#paypal_create_payment', as: :paypal_create_payment
  post 'orders/paypal/execute_payment'  => 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # root 'product#index'
  post 'orders/paypal/create_subscription'  => 'orders#paypal_create_subscription', as: :paypal_create_subscription
  post 'orders/paypal/execute_subscription'  => 'orders#paypal_execute_subscription', as: :paypal_execute_subscription
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p>Find me in app/views/home/index.html.erbvvr</p>
<%= link_to 'sign_out', destroy_user_session_path, method: :delete %>
<%= link_to 'Edit Profile', edit_user_registration_path %>
<%= link_to 'Log in', user_session_path %>
<%= link_to 'Create Product', new_product_path%>