config/routes.rb
Rails.application.routes.draw do
  # get 'products/index'
  devise_for :users
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  get 'products/place_order', to: 'products#place_order', as: 'place_order'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :products 
  root 'products#index'
  resources :products
  root to: 'products#index'
  resources :comments
  resources :orders 
  post 'orders/paypal/create_payment'  => 'orders#paypal_create_payment', as: :paypal_create_payment
  post 'orders/paypal/execute_payment'  => 'orders#paypal_execute_payment', as: :paypal_execute_payment
  # root 'product#index'
  post 'orders/paypal/create_subscription'  => 'orders#paypal_create_subscription', as: :paypal_create_subscription
  post 'orders/paypal/execute_subscription'  => 'orders#paypal_execute_subscription', as: :paypal_execute_subscription
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :comments 
    has_one_attached :image
    monetize :price_cents
    has_many :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#   protect_from_forgery with: :exception
    # before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user! 
    before_action :initialize_session
    before_action :load_cart 

  def new
    @product= Product.new
  end
  def index
    if params[:search_by_name] && params[:search_by_name] != ""
      @product = Product.where("name: ?", params[:search_by_name])
      puts "hello"*100
    else
        @product= Product.all.with_attached_images
    end
    # session[:visit_count] ||=1
    # session[:visit_count] +=1
    # @visit_count = 1
  end

  def add_to_cart
    # session[:cart]<<params[:id]
    # redirect_to products_path
    id = params[:id].to_i
    session[:cart]<<id unless session[:cart].include?(id)
    redirect_to products_path
  end
  def place_order
  end
# def valid?
#     @product['name']  = "can't be blank" if product.name?
#     @product['price']   = "can't be blank" if product.price?
#     @product['quantity'] = "can't be blank" if product.quantity?
# end        
def create
    @product =Product.new(product_params)
    @product.user_id = current_user.id
    # @product.serial_number=Product.index_products_on_user_id.last
    # product.images.attach(params[:message][:images])
    authorize @product
    if @product.save
      redirect_to products_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end   
  def show
      @product = Product.find(params[:id])
  end
  def index
    # @products= current_user.products
    if (is_seller?)
      @products= current_user.products
    else
    @products= Product.all
    end
  end
  def remove_from_cart
    id=params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end
  def edit
      @product = Product.find(params[:id])
      authorize @product
  end
  def update
      @product =Product.find(params[:id])
      authorize @product
      @product.update(product_params)
      redirect_to product_path(@product)
  end
  def destroy
      @product = Product.find(params[:id])
      authorize @product
      @product.destroy
      redirect_to root_path
  end
private
  def product_params
      params.require(:product).permit(:name, :serial_number, :price_cents, :image)
  end
  def initialize_session
    session[:visit_count] ||=0
    session[:cart] ||=[]
  end
  def load_cart
    @cart=Product.find(session[:cart])
  end
  def is_seller?
    # puts (@users.find(params[:role]))*100
    # puts (users.find(params[:role]))*100
    current_user.role == 'Seller'
  end
  def is_buyer?
    # puts (@users.find(params[:role]))*100
    # puts (users.find(params[:role]))*100
    current_user.role == 'Buyer'
  end

  def set_product
    @product = Product.find(params[:id])
  end
protected
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :role, :picture)}
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= form_for @product, url: product_path(@product) do |form| %>
  Name: <%= form.text_field :name %>
  Serial_number: <%= form.text_field :serial_number %>
  Price: <%= form.text_field :price_cents %>
  Image: <%= form.file_field :image, direct_upload: true  %><br><br>
  <%= form.submit %>
<% end %>

app/views/products/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<% if is_buyer? %>
<h1>All Products</h1>
<div align="center" ,class='contain' >
<%= form_tag "/products", method: "GET" do %>
  <%= label_tag :search_by_name %>
  <%= text_field_tag :search_by_name, params[:search_by_name] %>
    <%= submit_tag "Search" %>
<% end %>
<details>
<summary> SHOPPING CART </summary>
<% if @cart.empty? %>
  <p>No items in cart  </p>
  <% else %>
<ul>
<% @cart.each do |product| %>
  <li><%= product.name%> 
  <p> <button style= "background-color:#6495ED;"><%= link_to 'Remove from cart', remove_from_cart_path(product), method: :delete %></button><br><br>
</li>
   <button style= "background-color:#6495ED;"><%= link_to 'Place Order', place_order_path ,method: :get %></button><br><br>
  <% end %>
</ul>  
  <% end %>

</details>
    </div>
<% else %>
<h1>All Your Products</h1>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<div align="center" ,class='contain' >
<% @products.each do |product| %>
<% if product.image.attached? %>
<p>
<%= image_tag product.image.variant(resize: "500x500") %>
</p>
<% end %>
 <b>Name: <%= product.name %><br></b>
  Price: <%= product.price_cents %>$<br>
  <% if @cart.include?(product)%>
  <p> <button style= "background-color:#6495ED;"><%= link_to 'Remove from cart', remove_from_cart_path(product), method: :delete %></button><br><br>
  <% end %>
<% if is_seller? %>
 <button style= "background-color:#87CEFA;"><%= link_to "Edit Product Details", edit_product_path(product) %></button>
 <button style= "background-color:#87CEFA;"><%= link_to 'Delete Product',  product_path(product),  data: { confirm: "Are you sure?"}, method: :delete %></button>
<% else %>
   <button style= "background-color:#6495ED;"><%= link_to 'Add to Cart', add_to_cart_path(product.id),method: :post %></button><br><br>
    <button style= "background-color:#87CEFA;"><%= link_to "Add Comment", new_comment_path(product_id: product.id) %> </button>
 <button style= "background-color:#87CEFA;"><%= link_to 'Show Comments', comment_path(product) %></button>
<% end %>
 <button style= "background-color:#87CEFA;"><%= link_to "Show Product Details", product_path(product) %></button>
<br><br>
<% end %>
    </div>

<%# <%= link_to 'sign_out', destroy_user_session_path, method: :delete %>
<%# <%= link_to 'Edit Profile', edit_user_registration_path %> 

app/views/products/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div align="center" ,class='contain' >
<h1> New Product </h1>
<%= form_for @product, url: products_path(@product) do |form| %><br><br>

  Name: <%= form.text_field :name, required: true %><br><br>

  Price: <%= form.text_field :price_cents, required: true, pattern: "[Z1-99999]+" %><br><br>

  Image: <%= form.file_field :image, direct_upload: true  %><br><br>

  <%= form.submit %>
<% end %>
    </div>

app/views/products/place_order.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br> 
<div align="center" ,class='contain' >
<h1> Your order has been placed </h1>
<br><br>
<h3> You have ordered the following products: </h3>
<br>
<% @cart.each do |product| %>
<% if product.image.attached? %>
<p>
<%= image_tag product.image.variant(resize: "500x500") %>
</p>
  <% end %>
  Name: <%= product.name%> 
  <br>
  Price: <%= product.price_cents%> $
  <br>
    <br>

  <% end %>
  <button style= "background-color:#87CEFA;"><%= link_to 'Return to All Products', products_path %></button><br><br>
    </div>

app/views/products/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div align="center" ,class='contain' >
<h1>All Comments of this Product</h1>
<br><br>
<% if @product.image.attached? %>
<p>
<%= image_tag @product.image.variant(resize: "500x500") %>
</p>
<% end %>Name: <%= @product.name %><br>
Price: <%= @product.price_cents %>$<br>
<% @product.comments.each do |comment| %>
Comment: <%= comment.body %><br>
Comment by: <%= User.find(comment.user_id).name  %><br>
Commented on : <%= comment.created_at.strftime("%Y-%m-%d %H:%M")%><br>
<br><br>
<% end%>
<button style= "background-color:#87CEFA;"><%= link_to 'Return to All Products', products_path %></button><br><br>

    </div>